{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Monaco;\f1\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;\f2\fnil\fcharset0 Menlo-Regular;
}
{\colortbl;\red255\green255\blue255;\red12\green99\blue153;\red242\green239\blue236;\red135\green135\blue135;
\red0\green0\blue0;\red237\green237\blue237;\red31\green118\blue44;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c46667\c66667;\cssrgb\c96078\c94902\c94118;\cssrgb\c60000\c60000\c60000;
\cssrgb\c0\c0\c0;\cssrgb\c94510\c94510\c94510;\cssrgb\c13333\c52549\c22745;\csgray\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl360\partightenfactor0

\f0\fs24 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 \shad\shadx0\shady-20\shadr0\shado255 \shadc0 os\cf4 \strokec4 \shad\shadx0\shady-20\shadr0\shado255 \shadc0 :\cf5 \strokec5 \shad\shadx0\shady-20\shadr0\shado255 \shadc0  osx\
\pard\pardeftab720\sl408\partightenfactor0
\cf5 \cb6 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \shad0 osx_image: xcode12.5\
language:swift\
\pard\pardeftab720\sl400\partightenfactor0

\f1 \cf7 \cb1 script:
\f2\fs22 \cf8 \kerning1\expnd0\expndtw0 \CocoaLigature0 xcodebuild clean build test -workspace TestCI.xcworkspace -scheme TestCI -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.5,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO}